module.exports = {
  projects: [
    {
      displayName: '@gistplus/core',
      preset: 'ts-jest',
      testEnvironment: 'node',
      rootDir: 'packages/core/typescript',
      testMatch: ['<rootDir>/src/__tests__/**/*.test.ts'],
      transform: { '^.+\\.ts$': 'ts-jest' },
      moduleFileExtensions: ['ts', 'js'],
    },
    {
      displayName: '@gistplus/client',
      preset: 'ts-jest',
      testEnvironment: 'node',
      rootDir: 'packages/client/typescript',
      testMatch: ['<rootDir>/src/__tests__/**/*.test.ts'],
      transform: { '^.+\\.ts$': 'ts-jest' },
      moduleFileExtensions: ['ts', 'js'],
    },
    {
      displayName: '@gistplus/server',
      preset: 'ts-jest',
      testEnvironment: 'node',
      rootDir: 'packages/server/typescript',
      testMatch: ['<rootDir>/src/__tests__/**/*.test.ts'],
      transform: { '^.+\\.ts$': 'ts-jest' },
      moduleFileExtensions: ['ts', 'js'],
    },
    {
      displayName: '@gistplus/gateway',
      preset: 'ts-jest',
      testEnvironment: 'node',
      rootDir: 'packages/gateway/typescript',
      testMatch: ['<rootDir>/src/__tests__/**/*.test.ts'],
      transform: { '^.+\\.ts$': 'ts-jest' },
      moduleFileExtensions: ['ts', 'js'],
    },
    {
      displayName: '@gistplus/indexer',
      preset: 'ts-jest',
      testEnvironment: 'node',
      rootDir: 'packages/indexer/typescript',
      testMatch: ['<rootDir>/src/__tests__/**/*.test.ts'],
      transform: { '^.+\\.ts$': 'ts-jest' },
      moduleFileExtensions: ['ts', 'js'],
    },
  ],
  passWithNoTests: true,
};
